<?php
/**
 * @author Rufusy Idachi <idachirufus@gmail.com>
 * @date: 2/7/2023
 * @time: 11:52 AM
 */

/**
 * @var string $recipient
 *  @var string $regNumber
 */
?>

<tr>
    <td class="email-body" width="100%" cellpadding="0" cellspacing="0"
        style="word-break: break-word; margin: 0; padding: 0; font-family: &quot;Nunito Sans&quot;, Helvetica, Arial, sans-serif; font-size: 16px; width: 100%; -premailer-width: 100%; -premailer-cellpadding: 0; -premailer-cellspacing: 0; background-color: #FFFFFF;"
        bgcolor="#FFFFFF">
        <table class="email-body_inner" align="center" width="570" cellpadding="0" cellspacing="0" role="presentation"
               style="width: 570px; -premailer-width: 570px; -premailer-cellpadding: 0; -premailer-cellspacing: 0; background-color: #FFFFFF; margin: 0 auto; padding: 0;"
               bgcolor="#FFFFFF">
            <!-- Body content -->
            <tr>
                <td class="content-cell"
                    style="word-break: break-word; font-family: &quot;Nunito Sans&quot;, Helvetica, Arial, sans-serif; font-size: 16px; padding: 35px;">
                    <div class="f-fallback">
                        <p style="margin-top: 0; color: #333333; font-size: 22px; font-weight: bold; text-align: left;">
                            <?= $recipient ?>,
                        </p>

                        <p style="font-size: 16px; line-height: 1.625; color: #51545E; margin: .4em 0 1.1875em;">
                            Your registration into the University of Nairobi is now complete, and you have been assigned a student registration number.
                            Your registration number is <?= $regNumber?>.
                            The student registration number is an important identification in all your university undertakings.
                            From now on, you will use your registration number to log in to your student portal.
                        </p>

                        <p style="font-size: 16px; line-height: 1.625; color: #51545E; margin: .4em 0 1.1875em;">
                            Log into the student portal and report to the current session and register for courses.
                        </p>

                        <p style="font-size: 16px; line-height: 1.625; color: #51545E; margin: .4em 0 1.1875em;">
                            I take this opportunity to warmly welcome you to the university of Nairobi
                        </p>

                        <p style="font-size: 16px; line-height: 1.625; color: #51545E; margin: .4em 0 1.1875em;">
                            Academic Registrar
                        </p>

                        <p style="font-size: 16px; line-height: 1.625; color: #51545E; margin: .4em 0 1.1875em;">
                            <strong>This is an autogenerated message. Please don't reply to it.</strong>
                        </p>
                    </div>
                </td>
            </tr>
        </table>
    </td>
</tr>